// thermopack/src/app/admin/components/config-gallery/config-gallery.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { MainService } from '../../../services/service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'admin-config-gallery',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './config-gallery.component.html',
  styles: ``
})
export class ConfigGalleryComponent {
  @Input() images: string[] = ['', '', '', ''];
  @Input() identifier: string = '';

  handleFileInput(event: any, index:number) {
    const file: File = event.target.files[0];
    const reader = new FileReader();
    reader.onload = (e: any) => {
      this.images[index] = e.target.result;
    };
    reader.readAsDataURL(file);
  }

  deleteImage(index: number) {
    this.images[index] = '';
  }

}

<div class="container">
  <div class="row">
    <div class="col-md-3 my-2">
      <label for="image1 + {{this.identifier}}">
        <input type="file" id="image1 + {{this.identifier}}" (change)="handleFileInput($event, 0)" style="display: none;">
        <img [src]="this.images[0] !== '' ? this.images[0] : 'https://via.placeholder.com/200'" alt="Imagen 1" class="img-fluid" style="cursor: pointer; max-width: 200px; max-height: 200px; width: auto; height: auto;">
      </label>
      <button *ngIf="this.images[0] !== ''" class="btn btn-link delete-button" (click)="deleteImage(0)">
        <i class="fas fa-trash-alt"></i>
      </button>
    </div>
    <div class="col-md-3 my-2">
      <label for="image2 + {{this.identifier}}">
        <input type="file" id="image2 + {{this.identifier}}" (change)="handleFileInput($event, 1)" style="display: none;">
        <img [src]="this.images[1] !== '' ? this.images[1] : 'https://via.placeholder.com/200'" alt="Imagen 2" class="img-fluid" style="cursor: pointer; max-width: 200px; max-height: 200px; width: auto; height: auto;"/>
      </label>
      <button *ngIf="this.images[1] !== ''" class="btn btn-link delete-button" (click)="deleteImage(1)">
        <i class="fas fa-trash-alt"></i>
      </button>
    </div>
    <div class="col-md-3 my-2">
      <label for="image3 + {{this.identifier}}">
        <input type="file" id="image3 + {{this.identifier}}" (change)="handleFileInput($event, 2)" style="display: none;">
        <img [src]="this.images[2] !== '' ? this.images[2] : 'https://via.placeholder.com/200'" alt="Imagen 3" class="img-fluid" style="cursor: pointer; max-width: 200px; max-height: 200px; width: auto; height: auto;"/>
      </label>
      <button *ngIf="this.images[2] !== ''" class="btn btn-link delete-button" (click)="deleteImage(2)">
        <i class="fas fa-trash-alt"></i>
      </button>
    </div>
    <div class="col-md-3 my-2">
      <label for="image4 + {{this.identifier}}">
        <input type="file" id="image4 + {{this.identifier}}" (change)="handleFileInput($event, 3)" style="display: none;">
        <img [src]="this.images[3] !== '' ? this.images[3] : 'https://via.placeholder.com/200'" alt="Imagen 4" class="img-fluid" style="cursor: pointer; max-width: 200px; max-height: 200px; width: auto; height: auto;"/>
      </label>
      <button *ngIf="this.images[3] !== ''" class="btn btn-link delete-button" (click)="deleteImage(3)">
        <i class="fas fa-trash-alt"></i>
      </button>
    </div>
  </div>
</div>

// thermopack-web/src/components/ConfigGallery.tsx
type Props = {
  images: string[]
  identifier: string
  onImagesChange: (images: string[], identifier: string) => void
}

export function ConfigGallery({ images, identifier, onImagesChange }: Props) {
  const handleFile = (event: React.ChangeEvent<HTMLInputElement>, index: number) => {
    const file = event.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = (e) => {
      const next = [...images]
      next[index] = String(e.target?.result ?? '')
      onImagesChange(next, identifier)
    }
    reader.readAsDataURL(file)
  }

  const deleteImage = (index: number) => {
    const next = [...images]
    next[index] = ''
    onImagesChange(next, identifier)
  }

  return (
    <div className="row">
      {images.map((src, index) => (
        <div key={index} className="col-md-3 mb-3">
          <div className="input-group mb-2">
            <input type="file" className="form-control" id={`file-${identifier}-${index}`} accept="image/*" onChange={(ev) => handleFile(ev, index)} />
            <label className="input-group-text" htmlFor={`file-${identifier}-${index}`}>
              Subir
            </label>
          </div>
          {src ? (
            <div>
              <img src={src} alt="" className="img-fluid rounded" />
              <button type="button" className="btn btn-sm btn-danger mt-1" onClick={() => deleteImage(index)}>
                Quitar
              </button>
            </div>
          ) : null}
        </div>
      ))}
    </div>
  )
}
