// thermopack/src/app/shared/components/pagination/pagination.component.ts
import { Component, Input } from '@angular/core';
import { MainService } from '../../../services/service';

@Component({
  selector: 'shared-pagination',
  standalone: true,
  imports: [],
  templateUrl: './pagination.component.html',
  styleUrl: './pagination.component.css'
})
export class PaginationComponent {
  currentPage: number = 1;

  @Input()
  public type!:string

  constructor(
    private service:MainService,
  ){}

  OnNextPage():void{
    this.service.nextPage(this.type);
    // this.updateCurrentPage(1);
  }
  updateCurrentPage(change: number): void {
    this.currentPage += change;

    if (change > 0) {
      this.OnNextPage();
    } else if (change < 0) {
      this.onPastPage();
    }
  }
  onPastPage():void{
    this.service.pastPage(this.type);
    // this.updateCurrentPage(-1);
  }
  get offsetService():number{
    return this.service.offset;
  }
  get limitService():number{
    return this.service.limit;
  }
  get totalServices():number{
    return this.service.totalServices;
  }
  get offsetProducts():number{
    return this.service.offsetProducts;
  }
  get limitProducts():number{
    return this.service.limitProducts;
  }
  get totalProducts():number{

    return this.service.totalProducts;
  }
  generatePagination(): number[] {
    let totalPages =0
    if (this.type=="0") {
       totalPages = Math.ceil(this.totalServices / this.limitService);
    }else{
       totalPages = Math.ceil(this.totalProducts / this.limitProducts);
    }
    let startPage = 1;
    const paginationItems: number[] = [];

    if (totalPages > 3) {
      if (this.currentPage > 1 && this.currentPage < totalPages) {
        startPage = this.currentPage - 1;
      } else if (this.currentPage === totalPages) {
        startPage = totalPages - 2;
      }
    }

    for (let i = 0; i < 3 && startPage <= totalPages; i++, startPage++) {
      paginationItems.push(startPage);
    }
    return paginationItems;
  }


}

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    @if (this.type=="0") {
      @if (offsetService!==0) {
        <li cclass="page-item">
          <a class="page-link" (click)="updateCurrentPage(-1)" >Previous</a>
        </li>
      }
    }@else {
      @if (offsetProducts!==0) {
        <li cclass="page-item">
          <a class="page-link" (click)="updateCurrentPage(-1)" >Previous</a>
        </li>
      }
    }

    @for (pageNumber of generatePagination(); track $index) {
      <li class="page-item"  [class.active]="pageNumber === currentPage">
        <a class="page-link" (click)="updateCurrentPage(pageNumber - currentPage)">{{ pageNumber }}</a>
      </li>
    }
    
    @if (this.type=="0") {
      @if (totalServices>limitService) {
        <li class="page-item">
          <a class="page-link" (click)="updateCurrentPage(1)">Next</a>
        </li>
      }
    }@else {
      @if (totalProducts>limitProducts) {
        <li class="page-item">
          <a class="page-link" (click)="updateCurrentPage(1)">Next</a>
        </li>
      }
    }

  </ul>
</nav>

// thermopack-web/src/components/Pagination.tsx
import { useCallback, useMemo, useState, useEffect } from 'react'
import { useCatalogStore } from '../stores/catalogStore'
import { LIMIT_PRODUCTS, LIMIT_SERVICE } from '../stores/limits'

type Props = {
  type: '0' | '1'
  totalServices: number
  totalProducts: number
}

export function Pagination({ type, totalServices, totalProducts }: Props) {
  const { offsetServices, offsetProducts, nextPage, pastPage } = useCatalogStore()
  const limitService = LIMIT_SERVICE
  const limitProducts = LIMIT_PRODUCTS

  const offset = type === '0' ? offsetServices : offsetProducts
  const limit = type === '0' ? limitService : limitProducts
  const total = type === '0' ? totalServices : totalProducts

  const [currentPage, setCurrentPage] = useState(1)

  useEffect(() => {
    setCurrentPage(Math.floor(offset / limit) + 1)
  }, [offset, limit])

  const totalPages = Math.ceil(total / limit) || 1

  const generatePagination = useCallback((): number[] => {
    let startPage = 1
    const paginationItems: number[] = []
    if (totalPages > 3) {
      if (currentPage > 1 && currentPage < totalPages) {
        startPage = currentPage - 1
      } else if (currentPage === totalPages) {
        startPage = totalPages - 2
      }
    }
    for (let i = 0; i < 3 && startPage <= totalPages; i++, startPage++) {
      paginationItems.push(startPage)
    }
    return paginationItems
  }, [currentPage, totalPages])

  const updateCurrentPage = (change: number) => {
    setCurrentPage((p) => p + change)
    if (change > 0) nextPage(type)
    else if (change < 0) pastPage(type)
  }

  const pages = useMemo(() => generatePagination(), [generatePagination])

  return (
    <nav aria-label="Page navigation example">
      <ul className="pagination justify-content-center">
        {type === '0' ? (
          offsetServices !== 0 ? (
            <li className="page-item">
              <button type="button" className="page-link" onClick={() => updateCurrentPage(-1)}>
                Previous
              </button>
            </li>
          ) : null
        ) : offsetProducts !== 0 ? (
          <li className="page-item">
            <button type="button" className="page-link" onClick={() => updateCurrentPage(-1)}>
              Previous
            </button>
          </li>
        ) : null}

        {pages.map((pageNumber) => (
          <li key={pageNumber} className={'page-item' + (pageNumber === currentPage ? ' active' : '')}>
            <button type="button" className="page-link" onClick={() => updateCurrentPage(pageNumber - currentPage)}>
              {pageNumber}
            </button>
          </li>
        ))}

        {type === '0' ? (
          totalServices > limitService ? (
            <li className="page-item">
              <button type="button" className="page-link" onClick={() => updateCurrentPage(1)}>
                Next
              </button>
            </li>
          ) : null
        ) : totalProducts > limitProducts ? (
          <li className="page-item">
            <button type="button" className="page-link" onClick={() => updateCurrentPage(1)}>
              Next
            </button>
          </li>
        ) : null}
      </ul>
    </nav>
  )
}
