// thermopack-web/src/pages/LoginPage.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import bcrypt from 'bcryptjs'
import { useAuth } from '../auth/AuthContext'
import { getUserByEmail, forgotPassword } from '../api/users'
import { showAlert } from '../lib/sweetAlert'

export function LoginPage() {
  const { login } = useAuth()
  const navigate = useNavigate()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [passwordFieldType, setPasswordFieldType] = useState<'password' | 'text'>('password')
  const [passwordIcon, setPasswordIcon] = useState('/assets/icons/visibility.svg')

  const submitUserLogin = () => {
    if (email === '') return
    void getUserByEmail(email).then((user) => {
      if (!user || Object.keys(user).length === 0) {
        showAlert('Error', 'El correo no se encuentra registrado', 'error')
        return
      }
      bcrypt.compare(password, user.password, (err, result) => {
        if (err) {
          showAlert('Error', `Error al comparar contraseñas: ${String(err)}`, 'error')
          return
        }
        if (!result) {
          showAlert('Error', 'Contraseña equivocada', 'error')
          return
        }
        login(user)
        navigate('/admin/config/home')
      })
    })
  }

  const togglePasswordVisibility = () => {
    if (passwordFieldType === 'password') {
      setPasswordFieldType('text')
      setPasswordIcon('/assets/icons/visibility_off.svg')
    } else {
      setPasswordFieldType('password')
      setPasswordIcon('/assets/icons/visibility.svg')
    }
  }

  const forgot = () => {
    if (email === '') {
      showAlert('Error', 'Debe ingresar un correo', 'error')
      return
    }
    void getUserByEmail(email).then((user) => {
      if (!user || Object.keys(user).length === 0) {
        showAlert('Error', 'El correo ingresado no se encuentra ingresado', 'error')
        return
      }
      void forgotPassword(email, user.privileges)
      showAlert('Información', 'Se le ha enviado a su correo la nueva contraseña', 'info')
    })
  }

  return (
    <div className="container py-5" style={{ maxWidth: 480 }}>
      <h2>Iniciar sesión</h2>
      <div className="mb-3">
        <label className="form-label">Correo</label>
        <input type="email" className="form-control" value={email} onChange={(e) => setEmail(e.target.value)} />
      </div>
      <div className="mb-3">
        <label className="form-label">Contraseña</label>
        <div className="input-group">
          <input
            type={passwordFieldType}
            className="form-control"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <button type="button" className="btn btn-outline-secondary" onClick={togglePasswordVisibility}>
            <img src={passwordIcon} alt="" width={20} height={20} />
          </button>
        </div>
      </div>
      <button type="button" className="btn btn-primary me-2" onClick={submitUserLogin}>
        Entrar
      </button>
      <button type="button" className="btn btn-link" onClick={forgot}>
        Olvidé mi contraseña
      </button>
    </div>
  )
}

// thermopack/src/app/admin/pages/login-page/login-page.component.ts
import { Component } from '@angular/core';
import { MainService } from './../../../services/service';
import { Users } from '../../../interfaces/users.interface';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { YesNoPipePipe } from '../../pipes/yes-no-pipe.pipe';
import { CommonModule } from '@angular/common';
import * as bcrypt from 'bcryptjs';

@Component({
  selector: 'admin-login-page',
  standalone: true,
  imports: [FormsModule, YesNoPipePipe, CommonModule],
  templateUrl: './login-page.component.html'
})
export class LoginPageComponent {
  constructor(
    private router: Router,
    private service: MainService
  ) {}

  public email: string = '';
  public password: string = '';
  public passwordFieldType: string = 'password';
  public passwordIcon: string = "assets/icons/visibility.svg";

  submitUserLogin(): void {
    if (this.email == '') { return; }
    this.service.getUserByEmail(this.email).subscribe((user) => {
      if (Object.keys(user).length == 0){
        console.log('no se encuentra el correo registrado');// TODO alert
        return;
      }
      bcrypt.compare(this.password, user.password, (err, result) => {
        if (err) {
          console.error('Error al comparar contraseñas:', err);// TODO alert
          return;
        }
        if (!result) {
          console.log('La contraseña no coincide');// TODO alert
          return;
        }
        console.log('log in');
        this.service.login(user);
        this.router.navigate(['/admin/config']);
      });
    });
  }

  togglePasswordVisibility() {
    this.passwordFieldType = this.passwordFieldType === 'password' ? 'text' : 'password';
    this.passwordIcon = this.passwordIcon === "assets/icons/visibility.svg" ? "assets/icons/visibility_off.svg" : "assets/icons/visibility.svg";
  }

}

<body style="background: linear-gradient(to top, #97bfe7, #d6e7f8)">
  <div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="row">
      <div class="col-md-8 d-flex flex-column justify-content-center vh-100">
        <img src="../../../../assets/images/ThermoPack_logo_no-bg.png" class="img-fluid" alt="Imagen de Bienvenida">
      </div>
      <div class="col-md-4 bg-white p-4 d-flex flex-column justify-content-center vh-100">
        <h2 class="text-center mb-4 fs-1">¡Bienvenido!</h2>

        <form class="mt-4">
          <div class="mb-3">
            <label for="inputEmail" class="form-label">Correo Electrónico</label>
            <input type="email" class="form-control" id="inputEmail" placeholder="Correo Electrónico" [(ngModel)]="this.email" name="email">
          </div>
          <div class="mb-3">
            <label for="inputPassword" class="form-label">Contraseña</label>
            <div class="d-flex align-items-center">
              <input type="{{ passwordFieldType }}" class="form-control me-1" id="inputPassword" placeholder="Contraseña" [(ngModel)]="password" name="password">
              <button type="button" class="btn btn-light" (click)="togglePasswordVisibility()">
                <img src="{{this.passwordIcon}}" alt="Visibilidad">
              </button>
            </div>
          </div>
          <button type="submit" class="mt-4 w-100 btn btn-primary-thermopack btn-lg btn-block" (click)="submitUserLogin()">Ingresar</button>
        </form>

        <p class="text-center mt-3"><a href="#" class="link-secondary link-offset-2-hover link-underline-opacity-0 link-underline-opacity-75-hover">Olvidé mi contraseña</a></p>
      </div>
    </div>
  </div>
</body>
