// thermopack/src/app/admin/pages/add-product-page/add-product-page.component.ts
import { Component } from '@angular/core';
import { NavbarComponent } from "../../components/navbar/navbar.component";
import { UnderConstructionComponent } from "../../../shared/components/under-construction/under-construction.component";
import { ConfigGalleryComponent } from '../../components/config-gallery/config-gallery.component';
import { FormsModule, UntypedFormControl, UntypedFormGroup } from '@angular/forms';
import { MainService } from '../../../services/service';
import { ActivatedRoute, Router } from '@angular/router';
import { Types } from '../../../interfaces/types.interface';
import { SelectTypeComponent } from '../../../shared/components/select-type/select-type.component';
import { CommonModule } from '@angular/common';
import { Brands } from '../../../interfaces/brands.interface';
import { SweetAlertService } from '../../services/sweet-alert.service';

import { Select2Data, Select2Module, Select2UpdateEvent } from 'ng-select2-component';

@Component({
    selector: 'admin-add-product-page',
    standalone: true,
    templateUrl: './add-product-page.component.html',
    styles: ``,
    imports: [ConfigGalleryComponent, NavbarComponent, UnderConstructionComponent, FormsModule, SelectTypeComponent, CommonModule, Select2Module]
})
export class AddProductPageComponent {
  constructor(
    private service: MainService,
    private sweetAlertService: SweetAlertService,
    private router: Router,
  ) {}

  async ngOnInit() {
    if (!this.service.isLoggedIn){ this.router.navigate(['/login']); }
    if (!(await this.service.userCanAdd())) {
      this.router.navigate(['admin/config/home']);
    }
    this.getData();;
  }

  public name: string = '';
  public description: string = '';
  public price: number = 0;
  public images: string[] = [];

  public type: string = '';
  public types: any[]=[];
  public selectedType: any = {value: '0', label: ''};

  public brand: string = '';
  public brands: any[]=[];
  public selectedBrand: any = {value: '0', label: ''};

  public categories: any[]=[];
  public category: string = '';
  public selectedCategory: any = {value: '0', label: ''};

  public subCategory: string = '';
  public selectedSubCategory: any = {value: '0', label: ''};

  getData(): void {
    this.service.getAllTypes().subscribe((types) => {
      for (let i = 0; i < types.length; i++) {
        this.types[i] = {value: types[i]._id, label: types[i].name};
      }
    });

    this.service.getAllBrands().subscribe((brands) => {
      for (let i = 0; i < brands.length; i++) {
        this.brands[i] = {value: brands[i]._id, label: brands[i].name};
      }
    });

    this.service.getAllCategories().subscribe((categories) => {
      for (let i = 0; i < categories.length; i++) {
        this.categories[i] = {value: categories[i]._id, label: categories[i].name};
      }
    });
  }

  selectType(event: Select2UpdateEvent<any>) {
    if(event.options.length > 0){
      this.selectedType = event.options[0];

      if(this.selectedType.value === this.selectedType.label){
        this.service.createType(this.selectedType.label).subscribe((response) => {
          this.selectedType.value = response._id;
        });
      }
    }else{
      this.selectedType = {}
    }
  }

  selectBrand(event: any) {
    if(event.options.length > 0){
      this.selectedBrand = event.options[0];

      if(this.selectedBrand.value === this.selectedBrand.label){
        this.service.createBrand(this.selectedBrand.label).subscribe((response) => {
          this.selectedBrand.value = response._id;
        });
      }
    }else{
      this.selectedBrand = {}
    }
  }

  selectCategory(event: any) {
    if(event.options.length > 0){
      this.selectedCategory = event.options[0];

      if(this.selectedCategory.value === this.selectedCategory.label){
        this.service.createCategory(this.selectedCategory.label).subscribe((response) => {
          this.selectedCategory.value = response._id;
        });
      }
    }else{
      this.selectedCategory = {}
    }
  }

  selectSubCategory(event: any) {
    if(event.options.length > 0){
      this.selectedSubCategory = event.options[0];

      if(this.selectedSubCategory.value === this.selectedSubCategory.label){
        this.service.createCategory(this.selectedSubCategory.label).subscribe((response) => {
          this.selectedSubCategory.value = response._id;
        });
      }
    }else{
      this.selectedSubCategory = {}
    }
  }

  handleFileInput(event: any) {
    const files: FileList = event.target.files;
    for (let i = 0; i < files.length; i++) {
      const file: File = files[i];
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.images.push(e.target.result);
      };
      reader.readAsDataURL(file);
    }
  }

  deleteImage(index: number) {
    this.images[index] = '';
    // this.images.splice(index, 1);
  }

  save(){
    console.log(this.name.trim().length<3 )
    if (!this.name ||this.name.trim().length<3 || !this.description||this.description.trim().length<5 ) {
      this.sweetAlertService.showAlert('Error', 'Todos los campos son obligatorios', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    if (this.images.length<1 ) {
      this.sweetAlertService.showAlert('Error', 'Debe seleccionar una o más imagenes', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    this.service.getProductByName(this.name).subscribe((product) => {
      if (Object.keys(product).length !== 0){
        this.sweetAlertService.showAlert('Error', 'Ya existe un producto llamado' + product.name, 'error');
        return;
      }

    });
      this.service.createProduct(this.name, this.description,
      this.selectedBrand.value, this.selectedType.value, this.price,
      this.selectedCategory.value, this.selectedSubCategory.value,
      this.images).subscribe((response) => {
      console.log(response)
    });


      this.sweetAlertService.showAlert('Éxito', 'Los datos se han guardado correctamente', 'success');

  }

  validateInput(event: KeyboardEvent) {
    const inputValue = event.key;

    // Verificar si el valor ingresado es un guión o un signo negativo
    if (inputValue === '-' || inputValue === '-') {
      event.preventDefault(); // Bloquear la entrada del usuario
    }
  }


}

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4">
      <h2>Agregar Producto</h2>
      <hr>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Nombre</p>
        </div>
        <div class="col-md-6">
          <input type="text" class="form-control" [(ngModel)]="name">
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Descripción</p>
        </div>
        <div class="col-md-6">
          <textarea class="form-control" [(ngModel)]="description"></textarea>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Precio</p>
        </div>
        <div class="col-md-6">
          <input type="number" class="form-control" [(ngModel)]="price">
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Marca</p>
        </div>
        <div class="col-md-6">

        <select2 [data]="brands"
          multiple
          autoCreate
          displaySearchStatus="hidden"
          (update)="selectBrand($event)"></select2>

        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Tipo</p>
        </div>
        <div class="col-md-6">

          <select2 [data]="types"
            multiple
            autoCreate
            displaySearchStatus="hidden"
            (update)="selectType($event)"></select2>

        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Categoría</p>
        </div>
        <div class="col-md-6">

          <select2 [data]="categories"
            multiple
            autoCreate
            displaySearchStatus="hidden"
            (update)="selectCategory($event)"></select2>

        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Subcategoría</p>
        </div>
        <div class="col-md-6">

          <select2 [data]="categories"
            multiple
            autoCreate
            displaySearchStatus="hidden"
            (update)="selectSubCategory($event)"></select2>

        </div>
      </div>
      <div class="row mb-4">
        <div class="col-md-3">
          <p class="text-responsive">Imágenes</p>
        </div>
        <div class="col-md-6">
          <div>
            <input type="file" multiple (change)="handleFileInput($event)" accept="image/*" style="margin-bottom: 10px;">
            <div>
              <span *ngFor="let image of images; let i = index" >
                <img *ngIf="this.images[i] !== ''" [src]="image" alt="Imagen seleccionada" style="max-height: 50px;">
                <button *ngIf="this.images[i] !== ''" class="btn btn-link delete-button" (click)="deleteImage(i)">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="offset-3 col-md-6">
          <button class="btn btn-success me-4" (click)="save()">Guardar</button>
        </div>
      </div>

    </div>
  </div>
</div>

// thermopack-web/src/pages/admin/AddProductPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { getAllTypes, createType } from '../../api/typesApi'
import { getAllBrands, createBrand } from '../../api/brands'
import { getAllCategories, createCategory } from '../../api/categories'
import { createProduct, getProductByName } from '../../api/products'
import { CreatableIdSelect, type Opt } from '../../components/CreatableIdSelect'
import { useAuth } from '../../auth/AuthContext'
import { showAlert } from '../../lib/sweetAlert'

export function AddProductPage() {
  const navigate = useNavigate()
  const { isLoggedIn, userCanAdd } = useAuth()

  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [price, setPrice] = useState(0)
  const [images, setImages] = useState<string[]>([])

  const [typeOptions, setTypeOptions] = useState<Opt[]>([])
  const [brandOptions, setBrandOptions] = useState<Opt[]>([])
  const [categoryOptions, setCategoryOptions] = useState<Opt[]>([])

  const [selectedType, setSelectedType] = useState<Opt | null>(null)
  const [selectedBrand, setSelectedBrand] = useState<Opt | null>(null)
  const [selectedCategory, setSelectedCategory] = useState<Opt | null>(null)
  const [selectedSubCategory, setSelectedSubCategory] = useState<Opt | null>(null)

  useEffect(() => {
    if (!isLoggedIn) navigate('/login')
    void userCanAdd().then((ok) => {
      if (!ok) navigate('/admin/config/home')
    })
  }, [isLoggedIn, navigate, userCanAdd])

  useEffect(() => {
    void getAllTypes().then((types) => setTypeOptions(types.map((t) => ({ value: t._id, label: t.name }))))
    void getAllBrands().then((b) => setBrandOptions(b.map((x) => ({ value: x._id, label: x.name }))))
    void getAllCategories().then((c) => setCategoryOptions(c.map((x) => ({ value: x._id, label: x.name }))))
  }, [])

  const ensureCreated = async (opt: Opt | null, createFn: (name: string) => Promise<{ _id?: string }>): Promise<Opt | null> => {
    if (!opt) return null
    if (opt.value === opt.label) {
      const r = await createFn(opt.label)
      if (r._id) return { value: r._id, label: opt.label }
    }
    return opt
  }

  const onTypeChange = async (opt: Opt | null) => {
    setSelectedType(await ensureCreated(opt, createType))
  }
  const onBrandChange = async (opt: Opt | null) => {
    setSelectedBrand(await ensureCreated(opt, createBrand))
  }
  const onCategoryChange = async (opt: Opt | null) => {
    setSelectedCategory(await ensureCreated(opt, createCategory))
  }
  const onSubCategoryChange = async (opt: Opt | null) => {
    setSelectedSubCategory(await ensureCreated(opt, createCategory))
  }

  const handleFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files) return
    for (let i = 0; i < files.length; i++) {
      const file = files[i]
      const reader = new FileReader()
      reader.onload = () => setImages((prev) => [...prev, String(reader.result ?? '')])
      reader.readAsDataURL(file)
    }
  }

  const save = () => {
    if (!name || name.trim().length < 3 || !description || description.trim().length < 5) {
      showAlert('Error', 'Todos los campos son obligatorios', 'error')
      return
    }
    if (images.filter(Boolean).length < 1) {
      showAlert('Error', 'Debe seleccionar una o más imagenes', 'error')
      return
    }
    if (!selectedBrand?.value || !selectedType?.value || !selectedCategory?.value || !selectedSubCategory?.value) {
      showAlert('Error', 'Seleccione marca, tipo, categoría y subcategoría', 'error')
      return
    }
    void getProductByName(name.trim()).then((product) => {
      if (product && Object.keys(product).length !== 0) {
        showAlert('Error', 'Ya existe un producto llamado ' + product.name, 'error')
        return
      }
      void createProduct(
        name.trim(),
        description.trim(),
        selectedBrand.value,
        selectedType.value,
        price,
        selectedCategory.value,
        selectedSubCategory.value,
        images
      ).then(() => {
        showAlert('Éxito', 'Los datos se han guardado correctamente', 'success')
      })
    })
  }

  return (
    <div className="container">
      <div className="row">
        <div className="col-md-12 mt-4">
          <h2>Agregar Producto</h2>
          <hr />
          <div className="row mb-3">
            <div className="col-md-3">Nombre</div>
            <div className="col-md-6">
              <input type="text" className="form-control" value={name} onChange={(e) => setName(e.target.value)} />
              {name.trim().length < 3 && <div className="text-danger">Debe tener al menos 3 caracteres</div>}
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-md-3">Descripción</div>
            <div className="col-md-6">
              <textarea className="form-control" value={description} onChange={(e) => setDescription(e.target.value)} />
              {description.trim().length < 5 && <div className="text-danger">Debe tener al menos 5 caracteres</div>}
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-md-3">Precio</div>
            <div className="col-md-6">
              <input
                type="number"
                className="form-control"
                value={price}
                onChange={(e) => setPrice(Number(e.target.value))}
                onKeyDown={(e) => {
                  if (e.key === '-') e.preventDefault()
                }}
              />
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-md-3">Marca</div>
            <div className="col-md-6">
              <CreatableIdSelect options={brandOptions} value={selectedBrand} onChange={(v) => void onBrandChange(v)} aria-label="Marca" />
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-md-3">Tipo</div>
            <div className="col-md-6">
              <CreatableIdSelect options={typeOptions} value={selectedType} onChange={(v) => void onTypeChange(v)} aria-label="Tipo" />
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-md-3">Categoría</div>
            <div className="col-md-6">
              <CreatableIdSelect options={categoryOptions} value={selectedCategory} onChange={(v) => void onCategoryChange(v)} aria-label="Categoría" />
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-md-3">Subcategoría</div>
            <div className="col-md-6">
              <CreatableIdSelect options={categoryOptions} value={selectedSubCategory} onChange={(v) => void onSubCategoryChange(v)} aria-label="Subcategoría" />
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-md-3">Imágenes</div>
            <div className="col-md-6">
              <div className="input-group mb-3">
                <input type="file" multiple accept="image/*" className="form-control" id="inputFile" onChange={handleFiles} />
                <label className="input-group-text" htmlFor="inputFile">
                  Seleccionar archivo
                </label>
              </div>
              <div>
                {images.map((image, i) =>
                  image ? (
                    <span key={i} className="me-2">
                      <img src={image} alt="" style={{ maxHeight: 50 }} />
                      <button type="button" className="btn btn-link" onClick={() => setImages((prev) => prev.map((x, j) => (j === i ? '' : x)))}>
                        <i className="fas fa-trash-alt" />
                      </button>
                    </span>
                  ) : null
                )}
              </div>
            </div>
          </div>
          <button type="button" className="btn btn-success" onClick={save}>
            Guardar
          </button>
        </div>
      </div>
    </div>
  )
}
