// thermopack/src/app/admin/pages/add-service-page/add-service-page.component.ts
import { Component } from '@angular/core';
import { NavbarComponent } from "../../components/navbar/navbar.component";
import { UnderConstructionComponent } from "../../../shared/components/under-construction/under-construction.component";
import { ConfigGalleryComponent } from '../../components/config-gallery/config-gallery.component';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MainService } from '../../../services/service';
import { ActivatedRoute, Router } from '@angular/router';
import { SweetAlertService } from '../../services/sweet-alert.service';

@Component({
    selector: 'admin-add-service-page',
    standalone: true,
    templateUrl: './add-service-page.component.html',
    styles: ``,
    imports: [ConfigGalleryComponent, NavbarComponent, UnderConstructionComponent, FormsModule, CommonModule]
})
export class AddServicePageComponent {

  public name: string = '';
  public description: string = '';
  public price: number = 0;
  public images: string[] = [];

  constructor(
    private service: MainService,
    private route: ActivatedRoute,
    private router: Router,
    private sweetAlertService: SweetAlertService
  ) {}

  ngOnInit() {
    if (!this.service.isLoggedIn){ this.router.navigate(['/login']); }
  }

  handleFileInput(event: any) {
    const files: FileList = event.target.files;
    for (let i = 0; i < files.length; i++) {
      const file: File = files[i];
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.images.push(e.target.result);
      };
      reader.readAsDataURL(file);
    }
  }

  deleteImage(index: number) {
    this.images[index] = '';
    // this.images.splice(index, 1);
  }

  insert(){
    if (!this.name ||this.name.trim().length<3 || !this.description||this.description.trim().length<5 ) {
      this.sweetAlertService.showAlert('Error', 'Todos los campos son obligatorios', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    if (this.images.length<1 ) {
      this.sweetAlertService.showAlert('Error', 'Debe seleccionar una o más imagenes', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    else{
      this.service.getServiceByName(this.name).subscribe((service) => {
        if (this.name !== service.name && Object.keys(service).length !== 0){
          this.sweetAlertService.showAlert('Error', 'Ya existe un servicio llamado' + service.name, 'error');
          return;
        }
          this.service.createService(this.name, this.description, this.price, this.images)
            .subscribe((response) => {
          //console.log(response)
          this.sweetAlertService.showAlert('Éxito', 'Los datos se han guardado correctamente', 'success');
        });
      });
    }

  }

  clear(){
    this.name = ''
    this.description = '';
    this.price = 0;
    this.images = [];
  }
  validateInput(event: KeyboardEvent) {
    const inputValue = event.key;

    // Verificar si el valor ingresado es un guión o un signo negativo
    if (inputValue === '-' || inputValue === '-') {
      event.preventDefault(); // Bloquear la entrada del usuario
    }
  }
}

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4">
      <h2>Agregar Servicio</h2>
      <hr>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Nombre</p>
        </div>
        <div class="col-md-6">
          <input type="text" class="form-control" [(ngModel)]="name">
          @if (name.length < 3) {
            <div class="text-danger">Debe tener al menos 3 caracteres</div>
          }
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Descripción</p>
        </div>
        <div class="col-md-6">
          <textarea class="form-control" [(ngModel)]="description"></textarea>
          @if (description.length < 5) {
            <div class="text-danger">Debe tener al menos 5 caracteres</div>
          }
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Precio</p>
        </div>
        <div class="col-md-6">
          <input type="number" class="form-control" [(ngModel)]="price" (keydown)="validateInput($event)">
        </div>
      </div>
    </div>
    <div class="row mb-4">
      <div class="col-md-3">
        <p class="text-responsive">Imágenes</p>
      </div>
      <div class="col-md-6">
        <div>
          <div class="input-group mb-3">
            <input type="file" multiple id="inputFile" (change)="handleFileInput($event)" accept="image/*" style="margin-bottom: 10px;">
            <label class="input-group-text" for="inputFile"
            >Seleccionar archivo</label
          >
          </div>
          <div>
            <span *ngFor="let image of images; let i = index" >
              <img *ngIf="this.images[i] !== ''" [src]="image" alt="Imagen seleccionada" style="max-height: 50px;">
              <button *ngIf="this.images[i] !== ''" class="btn btn-link delete-button" (click)="deleteImage(i)">
                <i class="fas fa-trash-alt"></i>
              </button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-4">
      <div class="offset-3 col-md-6">
        <button class="btn btn-success me-4" (click)="insert()">Agregar</button>
        <button class="btn btn-danger" (click)="clear()">Limpiar</button>
      </div>
    </div>
  </div>
</div>

// thermopack-web/src/pages/admin/AddServicePage.tsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { createService, getServiceByName } from '../../api/servicesApi'
import { useAuth } from '../../auth/AuthContext'
import { showAlert } from '../../lib/sweetAlert'

export function AddServicePage() {
  const navigate = useNavigate()
  const { isLoggedIn, userCanAdd } = useAuth()
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [price, setPrice] = useState(0)
  const [images, setImages] = useState<string[]>([])

  useEffect(() => {
    if (!isLoggedIn) navigate('/login')
    void userCanAdd().then((ok) => {
      if (!ok) navigate('/admin/config/home')
    })
  }, [isLoggedIn, navigate, userCanAdd])

  const handleFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files) return
    for (let i = 0; i < files.length; i++) {
      const reader = new FileReader()
      reader.onload = () => setImages((prev) => [...prev, String(reader.result ?? '')])
      reader.readAsDataURL(files[i])
    }
  }

  const insert = () => {
    if (!name || name.trim().length < 3 || !description || description.trim().length < 5) {
      showAlert('Error', 'Todos los campos son obligatorios', 'error')
      return
    }
    if (images.filter(Boolean).length < 1) {
      showAlert('Error', 'Debe seleccionar una o más imagenes', 'error')
      return
    }
    void getServiceByName(name).then((service) => {
      if (name !== service.name && service.name && Object.keys(service).length !== 0) {
        showAlert('Error', 'Ya existe un servicio llamado' + service.name, 'error')
        return
      }
      void createService(name, description, price, images).then(() => {
        showAlert('Éxito', 'Los datos se han guardado correctamente', 'success')
      })
    })
  }

  return (
    <div className="container">
      <div className="col-md-12 mt-4">
        <h2>Agregar Servicio</h2>
        <hr />
        <div className="row mb-3">
          <div className="col-md-3">Nombre</div>
          <div className="col-md-6">
            <input type="text" className="form-control" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Descripción</div>
          <div className="col-md-6">
            <textarea className="form-control" value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Precio</div>
          <div className="col-md-6">
            <input type="number" className="form-control" value={price} onChange={(e) => setPrice(Number(e.target.value))} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Imágenes</div>
          <div className="col-md-6">
            <div className="input-group mb-3">
              <input type="file" multiple accept="image/*" className="form-control" id="addSvcFiles" onChange={handleFiles} />
              <label className="input-group-text" htmlFor="addSvcFiles">
                Seleccionar archivo
              </label>
            </div>
            {images.map((im, i) =>
              im ? (
                <span key={i} className="me-2">
                  <img src={im} alt="" style={{ maxHeight: 50 }} />
                  <button type="button" className="btn btn-link" onClick={() => setImages((prev) => prev.filter((_, j) => j !== i))}>
                    <i className="fas fa-trash-alt" />
                  </button>
                </span>
              ) : null
            )}
          </div>
        </div>
        <button type="button" className="btn btn-success" onClick={insert}>
          Guardar
        </button>
      </div>
    </div>
  )
}
