// thermopack/src/app/admin/pages/edit-product-page/edit-product-page.component.ts
import { Component } from '@angular/core';
import { NavbarComponent } from "../../components/navbar/navbar.component";
import { UnderConstructionComponent } from "../../../shared/components/under-construction/under-construction.component";
import { ConfigGalleryComponent } from '../../components/config-gallery/config-gallery.component';
import { FormsModule } from '@angular/forms';
import { MainService } from '../../../services/service';
import { ActivatedRoute, Router } from '@angular/router';
import { Types } from '../../../interfaces/types.interface';
import { SelectTypeComponent } from '../../../shared/components/select-type/select-type.component';
import { CommonModule } from '@angular/common';
import { Brands } from '../../../interfaces/brands.interface';
import { SweetAlertService } from '../../services/sweet-alert.service';

import { Select2Data, Select2Module, Select2UpdateEvent } from 'ng-select2-component';

@Component({
    selector: 'admin-edit-product-page',
    standalone: true,
    templateUrl: './edit-product-page.component.html',
    styles: ``,
    imports: [ConfigGalleryComponent, NavbarComponent, UnderConstructionComponent, FormsModule, SelectTypeComponent, CommonModule, Select2Module]
})
export class EditProductPageComponent {
  constructor(
    private service: MainService,
    private route: ActivatedRoute,
    private sweetAlertService: SweetAlertService,
    private router: Router,
  ) {}

  async ngOnInit() {
    if (!this.service.isLoggedIn){ this.router.navigate(['/login']); }
    if (!(await this.service.userCanEdit())) {
      this.router.navigate(['admin/config/home']);
    }
    this.route.paramMap.subscribe(params => {
      this.getData(params.get('id'));;
    });
  }
  public originalName: string = '';
  public name: string = '';
  public description: string = '';
  public price: number = 0;
  public images: string[] = [];

  public type: string = '';
  public types: any[]=[];
  public selectedType: any = {value: '0', label: ''};

  public brand: string = '';
  public brands: any[]=[];
  public selectedBrand: any = {value: '0', label: ''};

  public categories: any[]=[];
  public category: string = '';
  public selectedCategory: any = {value: '0', label: ''};

  public subCategory: string = '';
  public selectedSubCategory: any = {value: '0', label: ''};

  public descriptionPast: string = '';
  public pricePast: number = 0;
  public imagesPast: string[] = [];
  public typePast: string = '';
  public brandPast: string = '';
  public categoryPast: string = '';
  public subCategoryPast: string = '';


  getData(title: string | null): void {
    if (title == null){
      return;
    }

    this.service.getProductByName(title).subscribe((product) => {
      this.name = this.originalName = product.name;
      this.description = product.description;
      this.price = product.price;
      this.brand = product.brandId;
      this.type = product.typeId;
      this.category = product.categoryId;
      this.subCategory = product.subcategoryId;
      this.images = product.images;
      this.imagesPast.push(...product.images)
    });

    this.service.getAllTypes().subscribe((types) => {
      for (let i = 0; i < types.length; i++) {
        this.types[i] = {value: types[i]._id, label: types[i].name};
      }
      this.selectedType = this.type;
    });

    this.service.getAllBrands().subscribe((brands) => {
      for (let i = 0; i < brands.length; i++) {
        this.brands[i] = {value: brands[i]._id, label: brands[i].name};
      }
      this.selectedBrand = this.brand;
    });

    this.service.getAllCategories().subscribe((categories) => {
      for (let i = 0; i < categories.length; i++) {
        this.categories[i] = {value: categories[i]._id, label: categories[i].name};
      }
      this.selectedCategory = this.category;
      this.selectedSubCategory = this.subCategory;
    });
  }

  selectType(event: any) {
    if(event.options.length > 0){
      this.selectedType = event.options[0];

      if(this.selectedType.value === this.selectedType.label){
        this.service.createType(this.selectedType.label).subscribe((response) => {
          this.selectedType.value = response._id;
        });
      }
    }else{
      this.selectedType = {}
    }
  }

  selectBrand(event: any) {
    if(event.options.length > 0){
      this.selectedBrand = event.options[0];

      if(this.selectedBrand.value === this.selectedBrand.label){
        this.service.createBrand(this.selectedBrand.label).subscribe((response) => {
          this.selectedBrand.value = response._id;
        });
      }
    }else{
      this.selectedBrand = {}
    }
  }

  selectCategory(event: any) {
    if(event.options.length > 0){
      this.selectedCategory = event.options[0];

      if(this.selectedCategory.value === this.selectedCategory.label){
        this.service.createCategory(this.selectedCategory.label).subscribe((response) => {
          this.selectedCategory.value = response._id;
        });
      }
    }else{
      this.selectedCategory = {}
    }
  }

  selectSubCategory(event: any) {
    if(event.options.length > 0){
      this.selectedSubCategory = event.options[0];

      if(this.selectedSubCategory.value === this.selectedSubCategory.label){
        this.service.createCategory(this.selectedSubCategory.label).subscribe((response) => {
          this.selectedSubCategory.value = response._id;
        });
      }
    }else{
      this.selectedSubCategory = {}
    }
  }

  handleFileInput(event: any) {
    const files: FileList = event.target.files;
    for (let i = 0; i < files.length; i++) {
      const file: File = files[i];
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.images.push(e.target.result);
      };
      reader.readAsDataURL(file);
    }
  }

  deleteImage(index: number) {
    this.images[index] = '';
    // this.images.splice(index, 1);
  }

  update(){
    if (!this.name ||this.name.trim().length<3 || !this.description||this.description.trim().length<5 ) {
      this.sweetAlertService.showAlert('Error', 'Todos los campos son obligatorios', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    if (this.images.length<1 ) {
      this.sweetAlertService.showAlert('Error', 'Debe seleccionar una o más imagenes', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    if(this.hasChanged() ){
      this.service.getProductByName(this.name).subscribe((product) => {
        if (this.name !== this.originalName && Object.keys(product).length !== 0){
          this.sweetAlertService.showAlert('Error', 'Ya existe un producto llamado' + product.name, 'error');
          return;
        }
        else{
          this.service.updateProductByName(this.originalName, this.name, this.description,
            this.selectedBrand.value, this.selectedType.value, this.price,
            this.selectedCategory.value, this.selectedSubCategory.value,
            this.images).subscribe((response) => {
              this.sweetAlertService.showAlert('Éxito', 'Los datos se han guardado correctamente', 'success');
            })
        }
      });
    }else{
      this.sweetAlertService.showAlert('Información', 'No se realizó ningún cambio, no hay nada que guardar', 'info');
    }


  }
  hasChanged(): boolean {
    // Verificar si los campos han sido modificados con respecto a los datos cargados del servidor
    if (
      this.name !== this.originalName ||
      this.description !== this.descriptionPast ||
      this.price !== this.pricePast ||
      this.type !== this.typePast ||
      this.brand !== this.brandPast ||
      this.category !== this.categoryPast ||
      this.subCategory !== this.subCategoryPast|| this.arraysAreEqual()
    ) {
      return true; // Hay cambios
    } else {
      return false; // No hay cambios
    }

  }

  arraysAreEqual(): boolean {
    // Verificar si los elementos de los arrays son iguales
    for (let i = 0; i < this.imagesPast.length; i++) {
      if(this.imagesPast[i]!==this.images[i]){
        break;
      }
      else {
        return false;
      }
    }
    return true;
  }
  validateInput(event: KeyboardEvent) {
    const inputValue = event.key;

    // Verificar si el valor ingresado es un guión o un signo negativo
    if (inputValue === '-' || inputValue === '-') {
      event.preventDefault(); // Bloquear la entrada del usuario
    }
  }



}

<div class="container">
  <!-- Parte 1: Página de Inicio -->
  <div class="row">
    <div class="col-md-12 mt-4">
      <h2>Editar Producto</h2>
      <hr>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Nombre</p>
        </div>
        <div class="col-md-6">
          <input type="text" class="form-control" [(ngModel)]="name">
          @if (name.trim().length < 3) {
            <div class="text-danger">Debe tener al menos 3 caracteres</div>
          }
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Descripción</p>
        </div>
        <div class="col-md-6">
          <textarea class="form-control" [(ngModel)]="description"></textarea>
          @if (description.trim().length<5) {
            <div class="text-danger">Debe tener al menos 5 caracteres</div>
          }
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Precio</p>
        </div>
        <div class="col-md-6">
          <input type="number" class="form-control" [(ngModel)]="price" (keydown)="validateInput($event)">
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Marca</p>
        </div>
        <div class="col-md-6">

          <select2 [data]="brands"
            autoCreate
            displaySearchStatus="always"
            [value]="brand"
            (update)="selectBrand($event)"></select2>

        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Tipo</p>
        </div>
        <div class="col-md-6">

          <select2 [data]="types"
            autoCreate
            displaySearchStatus="always"
            [value]="type"
            (update)="selectType($event)"></select2>

        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Categoría</p>
        </div>
        <div class="col-md-6">

          <select2 [data]="categories"
            autoCreate
            displaySearchStatus="always"
            [value]="category"
            (update)="selectCategory($event)"></select2>

        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Subcategoría</p>
        </div>
        <div class="col-md-6">

          <select2 [data]="categories"
            autoCreate
            displaySearchStatus="always"
            [value]="subCategory"
            (update)="selectSubCategory($event)"></select2>

        </div>
      </div>
      <div class="row mb-4">
        <div class="col-md-3">
          <p class="text-responsive">Imágenes</p>
        </div>
        <div class="col-md-6">
          <div>
            <input type="file" multiple (change)="handleFileInput($event)" accept="image/*"
              style="margin-bottom: 10px;">
            <div>
              <span *ngFor="let image of images; let i = index">
                <img *ngIf="this.images[i] !== ''" [src]="image" alt="Imagen seleccionada" style="max-height: 50px;">
                <button *ngIf="this.images[i] !== ''" class="btn btn-link delete-button" (click)="deleteImage(i)">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="offset-3 col-md-6">
          <button class="btn btn-success me-4" (click)="update()">Editar</button>
        </div>
      </div>
    </div>
  </div>
</div>

// thermopack-web/src/pages/admin/EditProductPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { getAllTypes, createType } from '../../api/typesApi'
import { getAllBrands, createBrand } from '../../api/brands'
import { getAllCategories, createCategory } from '../../api/categories'
import { getProductByName, updateProductByName } from '../../api/products'
import { CreatableIdSelect, type Opt } from '../../components/CreatableIdSelect'
import { useAuth } from '../../auth/AuthContext'
import { showAlert, showConfirmationAlert } from '../../lib/sweetAlert'

export function EditProductPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { isLoggedIn, userCanEdit } = useAuth()

  const [originalName, setOriginalName] = useState('')
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [price, setPrice] = useState(0)
  const [images, setImages] = useState<string[]>([])

  const [descriptionPast, setDescriptionPast] = useState('')
  const [pricePast, setPricePast] = useState(0)
  const [typePast, setTypePast] = useState('')
  const [brandPast, setBrandPast] = useState('')
  const [categoryPast, setCategoryPast] = useState('')
  const [subCategoryPast, setSubCategoryPast] = useState('')
  const [imagesPast, setImagesPast] = useState<string[]>([])

  const [typeOptions, setTypeOptions] = useState<Opt[]>([])
  const [brandOptions, setBrandOptions] = useState<Opt[]>([])
  const [categoryOptions, setCategoryOptions] = useState<Opt[]>([])

  const [selectedType, setSelectedType] = useState<Opt | null>(null)
  const [selectedBrand, setSelectedBrand] = useState<Opt | null>(null)
  const [selectedCategory, setSelectedCategory] = useState<Opt | null>(null)
  const [selectedSubCategory, setSelectedSubCategory] = useState<Opt | null>(null)

  useEffect(() => {
    if (!isLoggedIn) navigate('/login')
    void userCanEdit().then((ok) => {
      if (!ok) navigate('/admin/config/home')
    })
  }, [isLoggedIn, navigate, userCanEdit])

  useEffect(() => {
    const title = id ? decodeURIComponent(id) : ''
    if (!title) return
    const run = async () => {
      const types = await getAllTypes()
      const brands = await getAllBrands()
      const categories = await getAllCategories()
      const typeOpts = types.map((t) => ({ value: t._id, label: t.name }))
      const brandOpts = brands.map((b) => ({ value: b._id, label: b.name }))
      const catOpts = categories.map((c) => ({ value: c._id, label: c.name }))
      setTypeOptions(typeOpts)
      setBrandOptions(brandOpts)
      setCategoryOptions(catOpts)
      const product = await getProductByName(title)
      if (!product.name) return
      setOriginalName(product.name)
      setName(product.name)
      setDescription(product.description)
      setDescriptionPast(product.description)
      setPrice(product.price)
      setPricePast(product.price)
      setTypePast(product.typeId)
      setBrandPast(product.brandId)
      setCategoryPast(product.categoryId)
      setSubCategoryPast(product.subcategoryId)
      setImages([...product.images])
      setImagesPast([...product.images])
      const pick = (opts: Opt[], val: string) => ({ value: val, label: opts.find((o) => o.value === val)?.label ?? val })
      setSelectedType(pick(typeOpts, product.typeId))
      setSelectedBrand(pick(brandOpts, product.brandId))
      setSelectedCategory(pick(catOpts, product.categoryId))
      setSelectedSubCategory(pick(catOpts, product.subcategoryId))
    }
    void run()
  }, [id])

  const ensureCreated = async (opt: Opt | null, createFn: (name: string) => Promise<{ _id?: string }>): Promise<Opt | null> => {
    if (!opt) return null
    if (opt.value === opt.label) {
      const r = await createFn(opt.label)
      if (r._id) return { value: r._id, label: opt.label }
    }
    return opt
  }

  const arraysImagesChanged = () => {
    if (imagesPast.length !== images.length) return true
    for (let i = 0; i < imagesPast.length; i++) {
      if (imagesPast[i] !== images[i]) return true
    }
    return false
  }

  const hasChanged = () =>
    name !== originalName ||
    description !== descriptionPast ||
    price !== pricePast ||
    selectedType?.value !== typePast ||
    selectedBrand?.value !== brandPast ||
    selectedCategory?.value !== categoryPast ||
    selectedSubCategory?.value !== subCategoryPast ||
    arraysImagesChanged()

  const doUpdate = () => {
    if (!selectedBrand?.value || !selectedType?.value || !selectedCategory?.value || !selectedSubCategory?.value) {
      showAlert('Error', 'Seleccione marca, tipo, categoría y subcategoría', 'error')
      return
    }
    void getProductByName(name.trim()).then((product) => {
      if (name !== originalName && product && Object.keys(product).length !== 0) {
        showAlert('Error', 'Ya existe un producto llamado' + product.name, 'error')
        return
      }
      void updateProductByName(
        originalName,
        name.trim(),
        description.trim(),
        selectedBrand.value,
        selectedType.value,
        price,
        selectedCategory.value,
        selectedSubCategory.value,
        images
      ).then(() => {
        showAlert('Éxito', 'Los datos se han guardado correctamente', 'success')
      })
    })
  }

  const update = () => {
    if (!name || name.trim().length < 3 || !description || description.trim().length < 5) {
      showAlert('Error', 'Todos los campos son obligatorios', 'error')
      return
    }
    if (images.filter(Boolean).length < 1) {
      showAlert('Error', 'Debe seleccionar una o más imagenes', 'error')
      return
    }
    if (!hasChanged()) {
      showAlert('Información', 'No se realizó ningún cambio, no hay nada que guardar', 'info')
      return
    }
    showConfirmationAlert('Confirmación', '¿Está seguro que desea realizar cambios?', doUpdate)
  }

  const handleFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files) return
    for (let i = 0; i < files.length; i++) {
      const reader = new FileReader()
      reader.onload = () => setImages((prev) => [...prev, String(reader.result ?? '')])
      reader.readAsDataURL(files[i])
    }
  }

  return (
    <div className="container">
      <div className="col-md-12 mt-4">
        <h2>Editar Producto</h2>
        <hr />
        <div className="row mb-3">
          <div className="col-md-3">Nombre</div>
          <div className="col-md-6">
            <input type="text" className="form-control" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Descripción</div>
          <div className="col-md-6">
            <textarea className="form-control" value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Precio</div>
          <div className="col-md-6">
            <input
              type="number"
              className="form-control"
              value={price}
              onChange={(e) => setPrice(Number(e.target.value))}
              onKeyDown={(e) => {
                if (e.key === '-') e.preventDefault()
              }}
            />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Marca</div>
          <div className="col-md-6">
            <CreatableIdSelect
              options={brandOptions}
              value={selectedBrand}
              onChange={(v) => void ensureCreated(v, createBrand).then(setSelectedBrand)}
            />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Tipo</div>
          <div className="col-md-6">
            <CreatableIdSelect options={typeOptions} value={selectedType} onChange={(v) => void ensureCreated(v, createType).then(setSelectedType)} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Categoría</div>
          <div className="col-md-6">
            <CreatableIdSelect
              options={categoryOptions}
              value={selectedCategory}
              onChange={(v) => void ensureCreated(v, createCategory).then(setSelectedCategory)}
            />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Subcategoría</div>
          <div className="col-md-6">
            <CreatableIdSelect
              options={categoryOptions}
              value={selectedSubCategory}
              onChange={(v) => void ensureCreated(v, createCategory).then(setSelectedSubCategory)}
            />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Imágenes</div>
          <div className="col-md-6">
            <div className="input-group mb-3">
              <input type="file" multiple accept="image/*" className="form-control" id="editProdFiles" onChange={handleFiles} />
              <label className="input-group-text" htmlFor="editProdFiles">
                Agregar
              </label>
            </div>
            {images.map((im, i) =>
              im ? (
                <span key={i} className="me-2">
                  <img src={im} alt="" style={{ maxHeight: 50 }} />
                  <button type="button" className="btn btn-link" onClick={() => setImages((prev) => prev.filter((_, j) => j !== i))}>
                    <i className="fas fa-trash-alt" />
                  </button>
                </span>
              ) : null
            )}
          </div>
        </div>
        <button type="button" className="btn btn-success" onClick={update}>
          Guardar cambios
        </button>
      </div>
    </div>
  )
}
