// thermopack/src/app/admin/components/user-table/user-table.component.ts
import { Component, ElementRef, HostListener, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { YesNoPipePipe } from "../../pipes/yes-no-pipe.pipe";
import { CommonModule } from '@angular/common';
import { MainService } from '../../../services/service';
import { Users } from '../../../interfaces/users.interface';
import { SweetAlertService } from '../../services/sweet-alert.service';

interface UsersTableRow {
  userEmail: string;
  privAddItems: boolean;
  privEditItems: boolean;
  privDelItems: boolean;
  privCreateUsers: boolean;
  editable: boolean;
}

enum Privileges {
  EditText,
  AddItems,
  EditItems,
  DelItems
}

@Component({
    selector: 'admin-user-table',
    standalone: true,
    templateUrl: './user-table.component.html',
    styles: ``,
    imports: [FormsModule, YesNoPipePipe, CommonModule]
})
export class UserTableComponent {
  constructor(
    private service: MainService,
    private sweetAlertService: SweetAlertService
  ) {}

  ngOnInit() {
    this.getData();;
  }

  public users: UsersTableRow[] = [];
  public selectedUser : UsersTableRow | null = null;
  public isEditing : boolean = false
  public email: string = '';
  public originalEmail: string = '';
  public privileges: boolean[] = [false,false,false,false];

  @ViewChild('txtUserEmail')
  private txtUserEmail !: ElementRef<HTMLInputElement>;

  @ViewChild('txtUserPswrd')
  private txtUserPswrd !: ElementRef<HTMLInputElement>;

  @ViewChild('chkPrivEditText')
  chkPrivEditText !: ElementRef<HTMLInputElement>;

  @ViewChild('chkPrivAddItems')
  chkPrivAddItems !: ElementRef<HTMLInputElement>;

  @ViewChild('chkPrivEditItems')
  chkPrivEditItems !: ElementRef<HTMLInputElement>;

  @ViewChild('chkPrivDelItems')
  chkPrivDelItems !: ElementRef<HTMLInputElement>;

  @ViewChild('txtPrivEditText') txtPrivEditText!: ElementRef<HTMLInputElement>;
  @ViewChild('txtPrivAddItems') txtPrivAddItems!: ElementRef<HTMLInputElement>;
  @ViewChild('txtPrivEditItems') txtPrivEditItems!: ElementRef<HTMLInputElement>;
  @ViewChild('txtPrivDelItems') txtPrivDelItems!: ElementRef<HTMLInputElement>;

  public checkedPrivilages : boolean[] = [false, false, false, false];
  public EnumPrivileges = Privileges;

  @HostListener('document:click', ['$event'])
  handleDocumentClick(event: MouseEvent) {
    const target = event.target as HTMLElement;
    const table = document.getElementById('users-table');
    if (!(table?.contains(target) || this.isEditing)) {
      this.selectedUser = null;
    }
  }

  checkChange(event: Event, privilege : Privileges){
    this.privileges[privilege] = this.privileges[privilege] === false ? true : false;
    this.checkedPrivilages[privilege] = (<HTMLInputElement>event.target).checked
  }

  isEmail(email: string) {
    const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return regex.test(email);
  }

  addUser() : void{
    for (let i = 0; i < this.users.length; i++) {
      if (this.users[i].userEmail == this.email || !this.isEmail(this.email)){
        this.sweetAlertService.showAlert('Error', 'Ya existe un usuario con el mismo correo, por favor cambiarlo', 'error');
        return;
      }
    }
    const privilegesAsNumbers = this.privileges.map(privilege => privilege ? 1 : 0);
    this.service.createUser(this.email, privilegesAsNumbers).subscribe((user) => {
      if (user.email == this.email){
        this.sweetAlertService.showAlert('Éxito', 'Los datos se han guardado correctamente', 'success');
        this.reload();
        // location.reload();
      }
    });
  }

  reload(): void {
    this.email = '';
    this.checkedPrivilages = this.privileges = [false, false, false, false];

    const checkboxes = [
      this.txtPrivEditText.nativeElement,
      this.txtPrivAddItems.nativeElement,
      this.txtPrivEditItems.nativeElement,
      this.txtPrivDelItems.nativeElement
    ];

    checkboxes.forEach(checkbox => {
      checkbox.checked = false;
    });

    this.users = [];
    this.service.getAllUsers().subscribe((users) => {
      for (let i = 0; i < users.length; i++) {
        this.users.push({ userEmail: users[i].email, privAddItems: users[i].privileges[0] == 1, privEditItems: users[i].privileges[1] == 1, privDelItems: users[i].privileges[2] == 1, privCreateUsers: users[i].privileges[3] == 1, editable: false })
      }
    });
  }

  getData(): void {
    this.service.getAllUsers().subscribe((users) => {
      for (let i = 0; i < users.length; i++) {
        this.users.push({ userEmail: users[i].email, privAddItems: users[i].privileges[0] == 1, privEditItems: users[i].privileges[1] == 1, privDelItems: users[i].privileges[2] == 1, privCreateUsers: users[i].privileges[3] == 1, editable: false })
      }
    });
  }

  editUser(user: UsersTableRow): void {
    user.editable = true;
    this.isEditing = true;
    this.originalEmail = user.userEmail;
  }

  saveUser(user: UsersTableRow, index: number): void {

    for (let i = 0; i < this.users.length; i++) {
      if (!this.isEmail(user.userEmail) || (this.users[i].userEmail == user.userEmail && i != index)){
        this.sweetAlertService.showAlert('Error', 'El email  esta repetido o es invalido', 'error');
        return;
      }
    }

    if (!this.existSuperAdminWithout(user)){
      if (!user.privAddItems || !user.privCreateUsers || !user.privDelItems || !user.privEditItems){
        this.sweetAlertService.showAlert('Error', 'Para realizar cambios ocupa ser usuario super administrador', 'error');
        return;
      }
    }
    this.sweetAlertService.showConfirmationAlert(
      'Confirmación',
      '¿Está seguro que desea realizar cambios?',
      () => {
    this.service.getAllUsers().subscribe((users) => {
      const privilegesAsNumbers = [user.privAddItems ? 1 : 0, user.privEditItems ? 1 : 0,
                                   user.privDelItems ? 1 : 0, user.privCreateUsers ? 1 : 0]
      this.service.updateUserByEmail(users[index].email, user.userEmail, users[index].password, privilegesAsNumbers).subscribe((response) => {
        if (response.message == 'Successfully modified'){
          user.editable = false;
          this.isEditing = false;
          this.selectedUser = null;
          this.sweetAlertService.showAlert('Éxito', 'El usuario se ha actualizado correctamente', 'success');
          location.reload();
        }else{
          this.sweetAlertService.showAlert('Error', 'No se puedo actualizar correctamente', 'error');
        }
      });
    }); }
    );
  }

  existSuperAdminWithout(user: UsersTableRow): boolean {
    const index = this.users.indexOf(user);
    const newUsersList = [...this.users.slice(0, index), ...this.users.slice(index + 1)];
    for (const item of newUsersList) {
      if (item.privCreateUsers && item.privAddItems && item.privDelItems && item.privEditItems) {
        return true;
      }
    }
    this.sweetAlertService.showAlert('Error', 'Debe existir un usuario super administrador', 'error');
    return false;
  }

  deleteUser(user: UsersTableRow): void {
    // TODO alert dde confirmacion
    this.selectedUser = null;
    this.isEditing = false;

    if (this.existSuperAdminWithout(user)){
      this.service.deleteUserByEmail(user.userEmail).subscribe((response) => {
        if (response.message == 'Successfully deleted'){
          // TODO alert de listo
          this.sweetAlertService.showAlert('Éxito', 'El usuario se ha eliminado correctamente', 'success');
          this.users.splice(this.users.indexOf(user), 1);
        }else{
          this.sweetAlertService.showAlert('Error', 'No se ha podido eliminar correctamente el usuario', 'error');
        }
      });
    }
  }

  reset(user: UsersTableRow, index: number): void {
    user.editable = false;
    this.isEditing = false;
    this.selectedUser = null;

    this.service.getAllUsers().subscribe((users) => {
      user.userEmail = users[index].email;
      user.privAddItems = users[index].privileges[0] == 1 ? true : false;
      user.privEditItems = users[index].privileges[1] == 1 ? true : false;
      user.privDelItems = users[index].privileges[2] == 1 ? true : false;
      user.privCreateUsers = users[index].privileges[3] == 1 ? true : false;
    });
  }

}

<table class="table mx-auto mx-5" id="users-table">
  <thead>
    <tr>
      <th>Correo</th>
      <th>Contraseña</th>
      <th>Editar texto</th>
      <th>Agregar items</th>
      <th>Editar items</th>
      <th>Eliminar items</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <!--? En realidad, no hace falta mostrar la contraseña para que no ande viajando tanto por las APIs-->
    <tr class="align-middle">
      <td contentEditable #txtUserEmail>Agregar un correo</td>
      <td contentEditable #txtUserPswrd></td>
      <td>
        <span class="badge py-2 px-3 w-100"
          [ngClass]="{'text-bg-success': checkedPrivilages[EnumPrivileges.EditText],
                      'text-bg-danger': !checkedPrivilages[EnumPrivileges.EditText]}">
          <input type="checkbox" #txtPrivEditText id="chkPrivEditText"
            (change)="checkChange($event, EnumPrivileges.EditText)" #chkPrivEditText>
          <label class="form-check-label ms-2" for="chkPrivEditText">
            {{ checkedPrivilages[EnumPrivileges.EditText] | yesNoPipe: 'es' }}
          </label>
        </span>
      </td>
      <td>
        <span class="badge py-2 px-3 w-100"
          [ngClass]="{'text-bg-success': checkedPrivilages[EnumPrivileges.AddItems],
                      'text-bg-danger': !checkedPrivilages[EnumPrivileges.AddItems]}">
          <input type="checkbox" #txtPrivAddItems id="checkbox2"
            (change)="checkChange($event, EnumPrivileges.AddItems)" #chkPrivAddItems>
          <label class="form-check-label ms-2" for="checkbox2">
            {{ checkedPrivilages[EnumPrivileges.AddItems] | yesNoPipe: 'es' }}
          </label>
        </span>
      </td>
      <td>
        <span class="badge py-2 px-3 w-100"
          [ngClass]="{'text-bg-success': checkedPrivilages[EnumPrivileges.EditItems],
                      'text-bg-danger': !checkedPrivilages[EnumPrivileges.EditItems]}">
          <input type="checkbox" #txtPrivEditItems id="checkbox3"
            (change)="checkChange($event, EnumPrivileges.EditItems)" #chkPrivEditItems>
          <label class="form-check-label ms-2" for="checkbox3">
            {{ checkedPrivilages[EnumPrivileges.EditItems] | yesNoPipe: 'es' }}
          </label>
        </span>
      </td>
      <td>
        <span class="badge py-2 px-3 w-100"
          [ngClass]="{'text-bg-success': checkedPrivilages[EnumPrivileges.DelItems],
                      'text-bg-danger': !checkedPrivilages[EnumPrivileges.DelItems]}">
          <input type="checkbox" #txtPrivDelItems id="checkbox4"
            (change)="checkChange($event, EnumPrivileges.DelItems)" #chkPrivDelItems>
          <label class="form-check-label ms-2" for="checkbox4">
            {{ checkedPrivilages[EnumPrivileges.DelItems] | yesNoPipe: 'es' }}
          </label>
        </span>
      </td>

      <td class="w-25">
        <button class="btn btn-info text-light mx-auto" (click)="selectedUser = null; isEditing = false; addUser($event)">
          <img src="assets/icons/remove_person_icon.svg" alt="Eliminar" class="me-1">
          Agregar</button>
      </td>
    </tr>

    @for (user of users; track $index) {
    <tr class="align-middle" [class.table-primary]="user === selectedUser" (click)="selectedUser = user">
      <td [contentEditable]="user.editable">{{ user.userEmail }}</td>
      <td [contentEditable]="user.editable" style="font: password;">{{ user.userPswrd }}</td>
      <td>
        <span class="badge py-2 px-3 w-100" [ngClass]="{'text-bg-success': user.privEditText, 'text-bg-danger': !user.privEditText}">
          <input type="checkbox" [disabled]="!user.editable" [(ngModel)]="user.privEditText" id="checkbox1">
          <label class="form-check-label ms-2" for="checkbox1">{{ user.privEditText | yesNoPipe: 'es' }}</label>
        </span>
      </td>
      <td>
        <span class="badge py-2 px-3 w-100" [ngClass]="{'text-bg-success': user.privAddItems, 'text-bg-danger': !user.privAddItems}">
          <input type="checkbox" [disabled]="!user.editable" [(ngModel)]="user.privAddItems" id="checkbox2">
          <label class="form-check-label ms-2" for="checkbox2">{{ user.privAddItems | yesNoPipe: 'es' }}</label>
        </span>
      </td>
      <td>
        <span class="badge py-2 px-3 w-100" [ngClass]="{'text-bg-success': user.privEditItems, 'text-bg-danger': !user.privEditItems}">
          <input type="checkbox" [disabled]="!user.editable" [(ngModel)]="user.privEditItems" id="checkbox3">
          <label class="form-check-label ms-2" for="checkbox3">{{ user.privEditItems | yesNoPipe: 'es' }}</label>
        </span>
      </td>
      <td>
        <span class="badge py-2 px-3 w-100" [ngClass]="{'text-bg-success': user.privDelItems, 'text-bg-danger': !user.privDelItems}">
          <input type="checkbox" [disabled]="!user.editable" [(ngModel)]="user.privDelItems" id="checkbox4">
          <label class="form-check-label ms-2" for="checkbox4">{{ user.privDelItems | yesNoPipe: 'es' }}</label>
        </span>
      </td>

      <td class="w-25">
        @if (user === selectedUser && !user.editable) {
        <button class="btn btn-primary me-2 mx-auto" (click)="user.editable = true; isEditing = true">
          <img src="assets/icons/edit_note_icon.svg" alt="Editar" class="me-1">
          Editar</button>
        <button class="btn btn-danger mx-auto" (click)="selectedUser = null; isEditing = false">
          <img src="assets/icons/remove_person_icon.svg" alt="Eliminar" class="me-1">
          Eliminar</button>
        }

        @if (user === selectedUser && user.editable) {
        <button class="btn btn-info text-light me-2 mx-auto" (click)="user.editable = false; isEditing = false">
          <img src="assets/icons/check_circle_icon.svg" alt="Eliminar" class="me-1">
          Guardar</button>
        <button class="btn btn-secondary mx-auto" (click)="user.editable = false; isEditing = false">
          <img src="assets/icons/cancel_close_icon.svg" alt="Eliminar" class="me-1">
          Cancelar</button>
        }
      </td>
    </tr>
    }
  </tbody>
</table>

// thermopack-web/src/pages/admin/UserTable.tsx
import { useEffect, useState, useCallback } from 'react'
import { createUser, deleteUserByEmail, getAllUsers, updateUserByEmail } from '../../api/users'
import { showAlert, showConfirmationAlert } from '../../lib/sweetAlert'

export type UsersTableRow = {
  userEmail: string
  privAddItems: boolean
  privEditItems: boolean
  privDelItems: boolean
  privCreateUsers: boolean
  editable: boolean
}

function yn(v: boolean) {
  return v ? 'Sí' : 'No'
}

export function UserTable() {
  const [users, setUsers] = useState<UsersTableRow[]>([])
  const [selectedUser, setSelectedUser] = useState<UsersTableRow | null>(null)
  const [email, setEmail] = useState('')
  const [privileges, setPrivileges] = useState([false, false, false, false])
  const [checkedPriv, setCheckedPriv] = useState([false, false, false, false])

  const load = useCallback(() => {
    void getAllUsers().then((list) => {
      setUsers(
        list.map((u) => ({
          userEmail: u.email,
          privAddItems: u.privileges[0] === 1,
          privEditItems: u.privileges[1] === 1,
          privDelItems: u.privileges[2] === 1,
          privCreateUsers: u.privileges[3] === 1,
          editable: false,
        }))
      )
    })
  }, [])

  useEffect(() => {
    load()
  }, [load])

  const isEmail = (s: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)

  const reloadForm = () => {
    setEmail('')
    setPrivileges([false, false, false, false])
    setCheckedPriv([false, false, false, false])
    load()
  }

  const addUser = () => {
    for (const u of users) {
      if (u.userEmail === email || !isEmail(email)) {
        showAlert('Error', 'Ya existe un usuario con el mismo correo, por favor cambiarlo', 'error')
        return
      }
    }
    const privilegesAsNumbers = privileges.map((p) => (p ? 1 : 0))
    void createUser(email, privilegesAsNumbers).then((user) => {
      if (user.email === email) {
        showAlert('Éxito', 'Los datos se han guardado correctamente', 'success')
        reloadForm()
      }
    })
  }

  const existSuperAdminWithout = (user: UsersTableRow): boolean => {
    const index = users.indexOf(user)
    const others = [...users.slice(0, index), ...users.slice(index + 1)]
    for (const item of others) {
      if (item.privCreateUsers && item.privAddItems && item.privDelItems && item.privEditItems) {
        return true
      }
    }
    showAlert('Error', 'Debe existir un usuario super administrador', 'error')
    return false
  }

  const saveUser = (user: UsersTableRow, index: number) => {
    for (let i = 0; i < users.length; i++) {
      if (!isEmail(user.userEmail) || (users[i].userEmail === user.userEmail && i !== index)) {
        showAlert('Error', 'El email  esta repetido o es invalido', 'error')
        return
      }
    }
    if (!existSuperAdminWithout(user)) {
      if (!user.privAddItems || !user.privCreateUsers || !user.privDelItems || !user.privEditItems) {
        showAlert('Error', 'Para realizar cambios ocupa ser usuario super administrador', 'error')
        return
      }
    }
    showConfirmationAlert('Confirmación', '¿Está seguro que desea realizar cambios?', () => {
      void getAllUsers().then((all) => {
        const dbUser = all[index]
        if (!dbUser) return
        const privilegesAsNumbers = [
          user.privAddItems ? 1 : 0,
          user.privEditItems ? 1 : 0,
          user.privDelItems ? 1 : 0,
          user.privCreateUsers ? 1 : 0,
        ]
        void updateUserByEmail(dbUser.email, user.userEmail, dbUser.password, privilegesAsNumbers).then((response) => {
          if (response.message === 'Successfully modified') {
            setUsers((prev) =>
              prev.map((u) => (u === user ? { ...u, editable: false } : u))
            )
            setSelectedUser(null)
            showAlert('Éxito', 'El usuario se ha actualizado correctamente', 'success')
            window.location.reload()
          } else {
            showAlert('Error', 'No se puedo actualizar correctamente', 'error')
          }
        })
      })
    })
  }

  const deleteUser = (user: UsersTableRow) => {
    setSelectedUser(null)
    if (!existSuperAdminWithout(user)) return
    void deleteUserByEmail(user.userEmail).then((response) => {
      if (response.message === 'Successfully deleted') {
        showAlert('Éxito', 'El usuario se ha eliminado correctamente', 'success')
        setUsers((prev) => prev.filter((u) => u !== user))
      } else {
        showAlert('Error', 'No se ha podido eliminar correctamente el usuario', 'error')
      }
    })
  }

  const resetUser = (user: UsersTableRow, index: number) => {
    user.editable = false
    setSelectedUser(null)
    void getAllUsers().then((all) => {
      const db = all[index]
      if (!db) return
      user.userEmail = db.email
      user.privAddItems = db.privileges[0] === 1
      user.privEditItems = db.privileges[1] === 1
      user.privDelItems = db.privileges[2] === 1
      user.privCreateUsers = db.privileges[3] === 1
      setUsers([...users])
    })
  }

  const togglePriv = (idx: number) => {
    setPrivileges((p) => {
      const n = [...p]
      n[idx] = !n[idx]
      return n
    })
    setCheckedPriv((p) => {
      const n = [...p]
      n[idx] = !n[idx]
      return n
    })
  }

  return (
    <table className="table mx-auto mx-5" id="users-table">
      <thead>
        <tr>
          <th>Correo</th>
          <th>Agregar items</th>
          <th>Editar items</th>
          <th>Eliminar items</th>
          <th>Crear Usuarios</th>
          <th />
        </tr>
      </thead>
      <tbody>
        <tr className="align-middle">
          <td>
            <input type="text" className="border-0 bg-transparent" value={email} placeholder="Agregar un correo" onChange={(e) => setEmail(e.target.value)} />
          </td>
          {[0, 1, 2, 3].map((idx) => (
            <td key={idx}>
              <span className={`badge py-2 px-3 w-100 ${checkedPriv[idx] ? 'text-bg-success' : 'text-bg-danger'}`}>
                <input type="checkbox" checked={checkedPriv[idx]} onChange={() => togglePriv(idx)} />
                <label className="form-check-label ms-2">{yn(checkedPriv[idx])}</label>
              </span>
            </td>
          ))}
          <td className="w-25">
            <button
              type="button"
              className="btn btn-info text-light"
              onClick={() => {
                setSelectedUser(null)
                addUser()
              }}
            >
              <img src="/assets/icons/remove_person_icon.svg" alt="" className="me-1" />
              Agregar
            </button>
          </td>
        </tr>
        {users.map((user, index) => (
          <tr
            key={user.userEmail}
            className={'align-middle' + (user === selectedUser ? ' table-primary' : '')}
            onClick={() => setSelectedUser(user)}
          >
            <td>
              <input
                type="text"
                className="border-0 bg-transparent"
                style={{ width: `${Math.max(user.userEmail.length, 12)}ch` }}
                value={user.userEmail}
                disabled={!user.editable}
                onChange={(e) => {
                  const v = e.target.value
                  setUsers((prev) => prev.map((u) => (u === user ? { ...u, userEmail: v } : u)))
                }}
                onClick={(e) => e.stopPropagation()}
              />
            </td>
            {(['privAddItems', 'privEditItems', 'privDelItems', 'privCreateUsers'] as const).map((field) => (
              <td key={field}>
                <span className={`badge py-2 px-3 w-100 ${user[field] ? 'text-bg-success' : 'text-bg-danger'}`}>
                  <input
                    type="checkbox"
                    disabled={!user.editable}
                    checked={user[field]}
                    onChange={(e) => {
                      e.stopPropagation()
                      setUsers((prev) =>
                        prev.map((u) => (u === user ? { ...u, [field]: !u[field] } : u))
                      )
                    }}
                  />
                  <label className="form-check-label ms-2">{yn(user[field])}</label>
                </span>
              </td>
            ))}
            <td className="w-25">
              {selectedUser === user && !user.editable && (
                <>
                  <button
                    type="button"
                    className="btn btn-primary me-2"
                    onClick={(e) => {
                      e.stopPropagation()
                      setUsers((prev) =>
                        prev.map((u) => (u === user ? { ...u, editable: true } : u))
                      )
                    }}
                  >
                    <img src="/assets/icons/edit_note_icon.svg" alt="" className="me-1" />
                    Editar
                  </button>
                  <button type="button" className="btn btn-danger" onClick={(e) => { e.stopPropagation(); deleteUser(user) }}>
                    <img src="/assets/icons/remove_person_icon.svg" alt="" className="me-1" />
                    Eliminar
                  </button>
                </>
              )}
              {selectedUser === user && user.editable && (
                <>
                  <button type="button" className="btn btn-info text-light me-2" onClick={(e) => { e.stopPropagation(); saveUser(user, index) }}>
                    <img src="/assets/icons/check_circle_icon.svg" alt="" className="me-1" />
                    Guardar
                  </button>
                  <button type="button" className="btn btn-secondary" onClick={(e) => { e.stopPropagation(); resetUser(user, index) }}>
                    <img src="/assets/icons/cancel_close_icon.svg" alt="" className="me-1" />
                    Cancelar
                  </button>
                </>
              )}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
