// thermopack-web/src/pages/admin/EditServicePage.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { getServiceByName, updateServiceByName } from '../../api/servicesApi'
import { useAuth } from '../../auth/AuthContext'
import { showAlert, showConfirmationAlert } from '../../lib/sweetAlert'

export function EditServicePage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { isLoggedIn, userCanEdit } = useAuth()

  const [originalName, setOriginalName] = useState('')
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [price, setPrice] = useState(0)
  const [images, setImages] = useState<string[]>([])

  const [descriptionPast, setDescriptionPast] = useState('')
  const [pricePast, setPricePast] = useState(0)
  const [imagesPast, setImagesPast] = useState<string[]>([])

  useEffect(() => {
    if (!isLoggedIn) navigate('/login')
    void userCanEdit().then((ok) => {
      if (!ok) navigate('/admin/config/home')
    })
  }, [isLoggedIn, navigate, userCanEdit])

  useEffect(() => {
    const title = id ? decodeURIComponent(id) : ''
    if (!title) return
    void getServiceByName(title).then((service) => {
      if (!service.name) return
      setOriginalName(service.name)
      setName(service.name)
      setDescription(service.description)
      setDescriptionPast(service.description)
      setPrice(service.price)
      setPricePast(service.price)
      setImages([...service.images])
      setImagesPast([...service.images])
    })
  }, [id])

  const hasChanged = () =>
    name !== originalName || description !== descriptionPast || price !== pricePast || JSON.stringify(images) !== JSON.stringify(imagesPast)

  const doUpdate = () => {
    void getServiceByName(name).then((service) => {
      if (name !== originalName && service.name && Object.keys(service).length !== 0) {
        showAlert('Error', 'Ya existe un servicio llamado' + service.name, 'error')
        return
      }
      void updateServiceByName(originalName, name.trim(), description.trim(), price, images).then(() => {
        showAlert('Éxito', 'Los datos se han guardado correctamente', 'success')
      })
    })
  }

  const update = () => {
    if (!name || name.trim().length < 3 || !description || description.trim().length < 5) {
      showAlert('Error', 'Todos los campos son obligatorios', 'error')
      return
    }
    if (images.filter(Boolean).length < 1) {
      showAlert('Error', 'Debe seleccionar una o más imagenes', 'error')
      return
    }
    if (!hasChanged()) {
      showAlert('Información', 'No se realizó ningún cambio, no hay nada que guardar', 'info')
      return
    }
    showConfirmationAlert('Confirmación', '¿Está seguro que desea realizar cambios?', doUpdate)
  }

  const handleFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files) return
    for (let i = 0; i < files.length; i++) {
      const reader = new FileReader()
      reader.onload = () => setImages((prev) => [...prev, String(reader.result ?? '')])
      reader.readAsDataURL(files[i])
    }
  }

  return (
    <div className="container">
      <div className="col-md-12 mt-4">
        <h2>Editar Servicio</h2>
        <hr />
        <div className="row mb-3">
          <div className="col-md-3">Nombre</div>
          <div className="col-md-6">
            <input type="text" className="form-control" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Descripción</div>
          <div className="col-md-6">
            <textarea className="form-control" value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Precio</div>
          <div className="col-md-6">
            <input type="number" className="form-control" value={price} onChange={(e) => setPrice(Number(e.target.value))} />
          </div>
        </div>
        <div className="row mb-3">
          <div className="col-md-3">Imágenes</div>
          <div className="col-md-6">
            <div className="input-group mb-3">
              <input type="file" multiple accept="image/*" className="form-control" id="editSvcFiles" onChange={handleFiles} />
              <label className="input-group-text" htmlFor="editSvcFiles">
                Agregar
              </label>
            </div>
            {images.map((im, i) =>
              im ? (
                <span key={i} className="me-2">
                  <img src={im} alt="" style={{ maxHeight: 50 }} />
                  <button type="button" className="btn btn-link" onClick={() => setImages((prev) => prev.filter((_, j) => j !== i))}>
                    <i className="fas fa-trash-alt" />
                  </button>
                </span>
              ) : null
            )}
          </div>
        </div>
        <button type="button" className="btn btn-success" onClick={update}>
          Guardar cambios
        </button>
      </div>
    </div>
  )
}

// thermopack/src/app/admin/pages/edit-service-page/edit-service-page.component.ts
import { Component } from '@angular/core';
import { NavbarComponent } from "../../components/navbar/navbar.component";
import { UnderConstructionComponent } from "../../../shared/components/under-construction/under-construction.component";
import { ConfigGalleryComponent } from '../../components/config-gallery/config-gallery.component';
import { MainService } from '../../../services/service';
import { ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { SweetAlertService } from '../../services/sweet-alert.service';

@Component({
    selector: 'admin-edit-service-page',
    standalone: true,
    templateUrl: './edit-service-page.component.html',
    styles: ``,
    imports: [ConfigGalleryComponent, NavbarComponent, UnderConstructionComponent, FormsModule, CommonModule]
})
export class EditServicePageComponent {

  constructor(
    private service: MainService,
    private route: ActivatedRoute,
    private router: Router,
    private sweetAlertService: SweetAlertService
  ) {}

  ngOnInit() {
    if (!this.service.isLoggedIn){ this.router.navigate(['/login']); }
    this.route.paramMap.subscribe(params => {
      this.getData(params.get('id'));;
    });
  }

  public originalName: string = '';
  public name: string = '';
  public description: string = '';
  public price: number = 0;
  public images: string[] = [];

  public descriptionPast: string = '';
  public pricePast: number = 0;
  public imagesPast: string[] = [];

  getData(title: string | null): void {
    if (title == null){
      return;
    }

    this.service.getServiceByName(title).subscribe((service) => {
      this.name = this.originalName = service.name;
      this.description = service.description;
      this.price = service.price;
      this.images = service.images;

      this.descriptionPast = service.description;
      this.pricePast = service.price;
      this.imagesPast = service.images;
    });
  }

  handleFileInput(event: any) {
    const files: FileList = event.target.files;
    for (let i = 0; i < files.length; i++) {
      const file: File = files[i];
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.images.push(e.target.result);
      };
      reader.readAsDataURL(file);
    }
  }

  deleteImage(index: number) {
    this.images=this.images.splice(index, 1);
    console.log(this.images)
  }

  update(){
    if (!this.name ||this.name.trim().length<3 || !this.description||this.description.trim().length<5 ) {
      this.sweetAlertService.showAlert('Error', 'Todos los campos son obligatorios', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    if (this.images.length<1 ) {
      this.sweetAlertService.showAlert('Error', 'Debe seleccionar una o más imagenes', 'error');
      return; // Detener el proceso si falta algún campo obligatorio
    }
    console.log(this.images.length)
    if (this.hasChanged()) {
      this.sweetAlertService.showConfirmationAlert(
        'Confirmación',
        '¿Está seguro que desea realizar cambios?',
        () => {
          this.service.getServiceByName(this.name).subscribe((service) => {
            if (this.name !== this.originalName && Object.keys(service).length !== 0){
              this.sweetAlertService.showAlert('Error', 'Ya existe un servicio llamado' + service.name, 'error');
              return;
            }
            this.service.updateServiceByName(this.originalName, this.name, this.description, this.price, this.images)
              .subscribe((response) => {
            this.sweetAlertService.showAlert('Éxito', 'Los datos se han guardado correctamente', 'success');
          });
          });
        }
        );
      }else{
        this.sweetAlertService.showAlert('Información', 'No se realizó ningún cambio, no hay nada que guardar', 'info');
      }


  }

hasChanged(): boolean {
    // Verificar si los campos han sido modificados con respecto a los datos cargados del servidor
    if (
      this.originalName !== this.name ||
      this.description !== this.descriptionPast||
      this.price!==this.pricePast||
      this.images!==this.imagesPast
    ) {
      console.log(this.images!==this.imagesPast)
      return true; // Hay cambios
    } else {
      console.log(this.images, this.imagesPast)
      return false; // No hay cambios
    }
  }
  goBack(){
    this.router.navigate(['/admin/services']);
  }
  validateInput(event: KeyboardEvent) {
    const inputValue = event.key;

    // Verificar si el valor ingresado es un guión o un signo negativo
    if (inputValue === '-' || inputValue === '-') {
      event.preventDefault(); // Bloquear la entrada del usuario
    }
  }

}

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4">
      <h2>Editar Servicio</h2>
      <hr>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Nombre</p>
        </div>
        <div class="col-md-6">
          <input type="text" class="form-control" [(ngModel)]="name">
          @if (name.length < 3) {
            <div class="text-danger">Debe tener al menos 3 caracteres</div>
          }
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Descripción</p>
        </div>
        <div class="col-md-6">
          <textarea class="form-control" [(ngModel)]="description"></textarea>
          @if (description.length < 5) {
            <div class="text-danger">Debe tener al menos 5 caracteres</div>
          }
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-3">
          <p class="text-responsive">Precio</p>
        </div>
        <div class="col-md-6">
          <input type="number" class="form-control" [(ngModel)]="price" (keydown)="validateInput($event)">
        </div>
      </div>
    </div>
    <div class="row mb-4">
      <div class="col-md-3">
        <p class="text-responsive">Imágenes</p>
      </div>
      <div class="col-md-6">
        <div>
          <input type="file" multiple (change)="handleFileInput($event)" accept="image/*" style="margin-bottom: 10px;">
          <div>
            <span *ngFor="let image of images; let i = index" >
              <img *ngIf="this.images[i] !== ''" [src]="image" alt="Imagen seleccionada" style="max-height: 50px;">
              <button *ngIf="this.images[i] !== ''" class="btn btn-link delete-button" (click)="deleteImage(i)">
                <i class="fas fa-trash-alt"></i>
              </button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-4">
      <div class="offset-3 col-md-6">
        <button class="btn btn-success me-4 " (click)="update()">Editar</button>
        <button class="btn btn-danger" (click)="goBack()">Cancelar</button>
      </div>
    </div>
  </div>
</div>
